import logging

logger = logging.getLogger(__name__)

def generate_architecture_digest(
    app_name: str, org_slug: str, kb_files: dict[str, str], max_chars: int = 3800
) -> str:
    """Generate a high-density, compact architecture digest under 4,000 characters.
    
    Designed for instant prompt injection into AI IDEs (Antigravity skills, Cursor rules, Copilot instructions).
    """
    from . import okf

    # the brief is prose for agents: OKF frontmatter and the reserved index/log files carry nothing it needs
    kb_files = {p: okf.prose(c) for p, c in kb_files.items() if p == "index.md" or p.rsplit("/", 1)[-1] not in okf.RESERVED}
    sections = []
    
    # 1. Header
    sections.append(f"# 🣩 Architecture Brief: {org_slug}/{app_name}")
    
    # 2. System Overview from index.md
    index_content = kb_files.get("index.md", "")
    if index_content:
        paragraphs = [p.strip() for p in index_content.split("\n\n") if p.strip() and not p.strip().startswith("#")]
        if paragraphs:
            sections.append(f"## Overview\n{paragraphs[0]}")
            
    # 3. Entities & Services
    entities = []
    for path, content in kb_files.items():
        if path.startswith("entities/") and path.endswith(".md"):
            name = path.replace("entities/", "").replace(".md", "").replace("-", " ").title()
            lines = [l.strip() for l in content.splitlines() if l.strip() and not l.startswith("#")]
            first_line = lines[0] if lines else "Entity component"
            entities.append(f"- **{name}**: {first_line[:120]}")
            
    if entities:
        sections.append("## Core Entities & Services\n" + "\n".join(entities[:6]))

    # 4. APIs & Schemas
    api_spec = kb_files.get("summaries/api-spec.md", "")
    if api_spec:
        prefixes = ("-", "*", "`GET", "`POST", "`PUT", "`DELETE")
        endpoints = [l.strip() for l in api_spec.splitlines() if any(l.strip().startswith(p) for p in prefixes)]
        if endpoints:
            sections.append("## Key Endpoints\n" + "\n".join(endpoints[:6]))

    # 5. Key Decisions & Active Constraints
    decisions = []
    for path, content in kb_files.items():
        if path.startswith("decisions/") and path.endswith(".md"):
            title = path.replace("decisions/", "").replace(".md", "").replace("-", " ").title()
            for line in content.splitlines():
                if any(k in line.lower() for k in ["must", "only", "status:"]):
                    decisions.append(f"- **{title}**: {line.strip(' -*#')[:120]}")
                    break
                    
    if decisions:
        sections.append("## Architectural Invariants & Decisions\n" + "\n".join(decisions[:5]))

    # Footer note
    sections.append("\n> Auto-generated by NoX from this application's Open Knowledge Format knowledge base. See the full repository for details.")

    digest = "\n\n".join(sections)
    
    # Strictly enforce max_chars budget
    if len(digest) > max_chars:
        digest = digest[:max_chars - 60] + "\n\n... [Truncated for 4k character context budget]"

    return digest
