"""engine baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 01:43:16.989027

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('github_org', sa.String(), nullable=True),
    sa.Column('parent_org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgs_slug'), 'orgs', ['slug'], unique=True)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'ingesting', 'generating', 'in_review', 'published', 'failed', name='kbstatus'), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('git_repo_url', sa.String(), nullable=True),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('org_pr_url', sa.String(), nullable=True),
    sa.Column('gcs_archive_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_kbs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('git_repo_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'ingesting', 'generating', 'in_review', 'published', 'failed', name='kbstatus'), nullable=True),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_interface_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('interface_type', sa.Enum('rest_endpoint', 'grpc_service', 'event_topic', 'shared_model', 'sdk_client', name='interfacetype'), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('page_path', sa.String(), nullable=False),
    sa.Column('anchor_slug', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_interface_contracts_app_name'), 'org_interface_contracts', ['app_name'], unique=False)
    op.create_index(op.f('ix_org_interface_contracts_identifier'), 'org_interface_contracts', ['identifier'], unique=False)
    op.create_index(op.f('ix_org_interface_contracts_kb_id'), 'org_interface_contracts', ['kb_id'], unique=False)
    op.create_index(op.f('ix_org_interface_contracts_org_id'), 'org_interface_contracts', ['org_id'], unique=False)
    op.create_table('source_monitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('last_commit_sha', sa.String(), nullable=True),
    sa.Column('last_sync_state', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('incremental_enabled', sa.Boolean(), nullable=True),
    sa.Column('monitor_mode', sa.Enum('webhook', 'polling', name='monitormode'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_monitors')
    op.drop_index(op.f('ix_org_interface_contracts_org_id'), table_name='org_interface_contracts')
    op.drop_index(op.f('ix_org_interface_contracts_kb_id'), table_name='org_interface_contracts')
    op.drop_index(op.f('ix_org_interface_contracts_identifier'), table_name='org_interface_contracts')
    op.drop_index(op.f('ix_org_interface_contracts_app_name'), table_name='org_interface_contracts')
    op.drop_table('org_interface_contracts')
    op.drop_table('kb_events')
    op.drop_table('org_kbs')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_orgs_slug'), table_name='orgs')
    op.drop_table('orgs')
    # ### end Alembic commands ###
    for name in ('kbstatus', 'monitormode', 'interfacetype'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
