"""missions

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 04:24:31.970228

"""
from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('primary_kb_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('business', 'product', 'engineering', 'developer', 'build', 'verifying', 'done', name='missionstage'), nullable=False),
    sa.Column('verify_role', postgresql.ENUM('business', 'product', 'engineering', 'developer', name='role', create_type=False), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_as_role', postgresql.ENUM('business', 'product', 'engineering', 'developer', name='role', create_type=False), nullable=False),
    sa.Column('awaiting_proceed', sa.Boolean(), nullable=False),
    sa.Column('proceeded_without_approval', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_number'), 'missions', ['number'], unique=True)
    op.create_index(op.f('ix_missions_org_id'), 'missions', ['org_id'], unique=False)
    op.create_table('external_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'system', 'external_id', name='uq_external_link')
    )
    op.create_index(op.f('ix_external_links_external_id'), 'external_links', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_links_mission_id'), 'external_links', ['mission_id'], unique=False)
    op.create_table('mission_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'kb_id', name='uq_mission_app')
    )
    op.create_index(op.f('ix_mission_apps_mission_id'), 'mission_apps', ['mission_id'], unique=False)
    op.create_table('mission_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('acting_role', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_events_created_at'), 'mission_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_mission_events_mission_id'), 'mission_events', ['mission_id'], unique=False)
    op.create_table('spec_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('business', 'product', 'engineering', 'developer', name='role', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('empty', 'drafting', 'ai_drafted', 'draft', 'approved', 'stale', name='specstatus'), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('git_path', sa.String(), nullable=True),
    sa.Column('git_commit_sha', sa.String(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'role', name='uq_spec_file_role')
    )
    op.create_index(op.f('ix_spec_files_mission_id'), 'spec_files', ['mission_id'], unique=False)
    op.create_table('spec_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spec_file_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spec_file_id'], ['spec_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spec_chat_messages_spec_file_id'), 'spec_chat_messages', ['spec_file_id'], unique=False)
    op.create_table('spec_file_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spec_file_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('saved_by', sa.UUID(), nullable=True),
    sa.Column('git_commit_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['spec_file_id'], ['spec_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spec_file_versions_spec_file_id'), 'spec_file_versions', ['spec_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spec_file_versions_spec_file_id'), table_name='spec_file_versions')
    op.drop_table('spec_file_versions')
    op.drop_index(op.f('ix_spec_chat_messages_spec_file_id'), table_name='spec_chat_messages')
    op.drop_table('spec_chat_messages')
    op.drop_index(op.f('ix_spec_files_mission_id'), table_name='spec_files')
    op.drop_table('spec_files')
    op.drop_index(op.f('ix_mission_events_mission_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_created_at'), table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_index(op.f('ix_mission_apps_mission_id'), table_name='mission_apps')
    op.drop_table('mission_apps')
    op.drop_index(op.f('ix_external_links_mission_id'), table_name='external_links')
    op.drop_index(op.f('ix_external_links_external_id'), table_name='external_links')
    op.drop_table('external_links')
    op.drop_index(op.f('ix_missions_org_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_number'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
    for name in ('missionstage', 'specstatus'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
